services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: server
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
    networks:
      - mongodb_network
  mongodb:
    image: mongo:latest
    hostname: mongodb
    volumes:
      - mongodb-data:/data/db/
      - mongodb-log:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongodb_network

volumes:
  mongodb-data:
    name: mongo-data
    external: true
  mongodb-log:
    name: mongo-log
    external: true

networks:
  mongodb_network:
    name: mongo-network
    external: true